joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 400
  
force_torque_sensor_controller:
  type: force_torque_sensor_controller/ForceTorqueSensorController
  publish_rate: 400
  
my_controller:
  type: testing_controller/ForcePositionController
  publish_rate: 200
  required_drive_mode: 7
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  sensor: ForceTorqueSensorSim
  IKController:
    separation_matrix: [1,1,1,1,1,1]
    Frequency: 200.
    parallel: false
    pid_force_x: {p: 0.0002, i: 0.00, d: 0.0, i_clamp: 3.0, publish_state: true}
    pid_force_y: {p: 0.0002, i: 0.00, d: 0.0, i_clamp: 3.0, publish_state: true}
    pid_force_z: {p: 0.0002, i: 0.00, d: 0.0, i_clamp: 3.0, publish_state: true}
    pid_torque_x: {p: 0.005, i: 0.0, d: 0.0, i_clamp: 7.0, publish_state: true} 
    pid_torque_y: {p: 0.005, i: 0.0, d: 0.0, i_clamp: 7.0, publish_state: true}
    pid_torque_z: {p: 0.005, i: 0.0, d: 0.0, i_clamp: 7.0, publish_state: true}
    pid_pos_x: {p: 0.005, i: 0.0, d: 0.0, i_clamp: 3.0}
    pid_pos_y: {p: 0.005, i: 0.0, d: 0.0, i_clamp: 3.0}
    pid_pos_z: {p: 0.005, i: 0.0, d: 0.0, i_clamp: 3.0}
    pid_rot_x: {p: 0.025, i: 0.0, d: 0.0, i_clamp: 7.0}
    pid_rot_y: {p: 0.025, i: 0.0, d: 0.0, i_clamp: 7.0}
    pid_rot_z: {p: 0.025, i: 0.0, d: 0.0, i_clamp: 7.0}
  publish_force: true
  group: "arm"
  sensor_frame: fts_base_link
  IK_base_frame: base_link
  IK_endeffector: tool0
  endeffector_frame:  fts_tool_link
  world_frame: world
  controller_frame: base_link
  ik_type: "r5_arm_kinematics/IKFastKinematicsPlugin"
