CAN:
    type: SOCKETCAN           # CANITFTYPE_SOCKET_CAN
    path: can0
    baudrate: 1000000

FTS:
    base_identifier: 0xA
    auto_init: true
    fts_name: "Schunk_FTC_050"

Node:
    sim: false
    sensor_hw: "schunk_powercube/SchunkFtcHW"
    ft_pub_freq: 200
    ft_pull_freq: 800
    sensor_frame: "fts_reference_link"
    transform_frame: "fts_base_link"

Calibration:
    Offset:
        n_measurements: 500
        T_between_meas: 0.01
        isStatic: true # true= use static offset Calibration, false=use calibrate Sensor to 0 in current State

